"""Phase 1 payoff: score the forecasters honestly and write the scorecard.

Runs Persistence, Climatology, and a refit-per-fold LightGBM through the
leakage-free rolling-origin backtest, compares them on probabilistic accuracy
*and* dollars captured, and writes ``reports/phase1_scorecard.md``.

Usage:
    .venv/bin/python -m scripts.evaluate
    .venv/bin/python -m scripts.evaluate --folds 4 --horizons 1,6,24,72 --mw 100
"""
from __future__ import annotations

import argparse
import os
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ml.backtest import run_backtest  # noqa: E402
from ml.baselines import ClimatologyForecaster, PersistenceForecaster  # noqa: E402
from ml.forecasters import LightGBMQuantileForecaster  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARQUET = os.path.join(ROOT, "backend", "data", "historical_spreads.parquet")
REPORT = os.path.join(ROOT, "reports", "phase1_scorecard.md")


def _fmt_money(x: float) -> str:
    if x != x:  # NaN
        return "—"
    sign = "-" if x < 0 else ""
    return f"{sign}${abs(x):,.0f}"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--folds", type=int, default=4)
    ap.add_argument("--horizons", default="1,6,24,72")
    ap.add_argument("--mw", type=float, default=100.0)
    args = ap.parse_args()
    horizons = tuple(int(h) for h in args.horizons.split(","))

    df = pd.read_parquet(PARQUET)
    df["ts"] = pd.to_datetime(df["ts"])
    print(f"Loaded {len(df):,} rows | {df['site_id'].nunique()} sites | "
          f"{df['ts'].min()} -> {df['ts'].max()}")

    forecasters = {
        "Persistence": PersistenceForecaster,
        "Climatology": ClimatologyForecaster,
        "LightGBM (refit/fold)": LightGBMQuantileForecaster,
    }

    results = {}
    for name, factory in forecasters.items():
        print(f"\n▶ Backtesting {name} ...")
        results[name] = run_backtest(
            df, factory, name, horizons=horizons, n_folds=args.folds, mw=args.mw
        )
        r = results[name]
        print(f"   mean pinball = {r.overall['mean_pinball']:.3f} | "
              f"capture = {r.economics.get('capture_rate', float('nan')):.1%} | "
              f"savings = {_fmt_money(r.economics.get('policy_savings', float('nan')))}")

    _write_report(results, horizons, args)
    print(f"\n✅ Wrote {os.path.relpath(REPORT, ROOT)}")


def _write_report(results, horizons, args) -> None:
    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    best = min(results.values(), key=lambda r: r.overall["mean_pinball"])
    perfect = next(iter(results.values())).economics.get("perfect_foresight", float("nan"))

    lines = [
        "# Phase 1 Scorecard — Honest, Leakage-Free Evaluation",
        "",
        f"_Generated by `scripts/evaluate.py` · {args.folds} rolling-origin folds · "
        f"horizons {list(horizons)}h · {args.mw:.0f} MW facility._",
        "",
        "## How to read this",
        "- **mean pinball** — the proper accuracy metric for a quantile forecast "
        "(lower is better). Replaces the old MAE-only number.",
        "- **interval cov.** — how often the realized spread fell inside the p10–p90 "
        "band. Nominal target is **80%**; far from it = miscalibrated uncertainty.",
        "- **capture rate** — share of the theoretically available arbitrage value "
        "(perfect foresight) that following this forecast's GENERATE/IMPORT signal "
        "actually banks. This is the dollars metric.",
        "- **savings** — modeled value over a 90-day-ish window vs. always buying from "
        "the grid. Perfect-foresight ceiling ≈ " + _fmt_money(perfect) + ".",
        "",
        "## Overall (all horizons pooled)",
        "",
        "| Forecaster | mean pinball ↓ | interval cov. (→80%) | decision acc. | capture rate ↑ | savings ↑ |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for r in results.values():
        o, e = r.overall, r.economics
        flag = " **★**" if r is best else ""
        lines.append(
            f"| {r.name}{flag} | {o['mean_pinball']:.3f} | "
            f"{o.get('interval_coverage', float('nan')):.0%} | "
            f"{e.get('decision_accuracy', float('nan')):.0%} | "
            f"{e.get('capture_rate', float('nan')):.1%} | "
            f"{_fmt_money(e.get('policy_savings', float('nan')))} |"
        )

    lines += ["", "## Per-horizon mean pinball (lower is better)", "",
              "| Forecaster | " + " | ".join(f"{h}h" for h in horizons) + " |",
              "|---|" + "---:|" * len(horizons)]
    for r in results.values():
        cells = [f"{r.per_horizon.get(h, {}).get('mean_pinball', float('nan')):.3f}"
                 for h in horizons]
        lines.append(f"| {r.name} | " + " | ".join(cells) + " |")

    lines += ["", "## Per-horizon capture rate (dollars banked vs. ceiling)", "",
              "| Forecaster | " + " | ".join(f"{h}h" for h in horizons) + " |",
              "|---|" + "---:|" * len(horizons)]
    for r in results.values():
        cells = [f"{r.per_horizon.get(h, {}).get('capture_rate', float('nan')):.0%}"
                 for h in horizons]
        lines.append(f"| {r.name} | " + " | ".join(cells) + " |")

    lines += [
        "",
        "## The point",
        f"The strongest model by pinball is **{best.name}**. The bar it had to clear "
        "is the persistence baseline — *no model ships unless it beats persistence on "
        "this leakage-free backtest.* The capture-rate column translates accuracy into "
        "the only thing a customer cares about: dollars of arbitrage actually banked.",
        "",
        "> Note on the *old* numbers: the previous `train_spread_forecaster.py` reported "
        "MAE from a split that grouped rows by site before slicing, leaking overlapping "
        "future timestamps into training. Those figures were optimistic; everything above "
        "is measured with strictly-past training and an embargo ≥ the max horizon.",
        "",
    ]
    with open(REPORT, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
